spring:
  application:
    name: user-service
  # cloud:
  #   vault:
  #     enabled: true
  #     port: 8200
  #     scheme: http
  #     authentication: TOKEN
  #     token: 00000000-0000-0000-0000-000000000000
  #     application-name: appx
  #     kv:
  #       enabled: true
  #       backend: secret
  #       default-context: appx
  # config:
  #   import: optional:vault://


server:
  port: ${VPORT:8080}

appx:
  modules:
    vault:
      enabled: true
    services:
      user-auth-service: http://USER-AUTH-SERVICE/api/users



# logging.level.org.springframework.cloud: TRACE
