spring:
  application:
    name: user-service
  cloud:
    vault:
      port: 8200
      scheme: http
      authentication: TOKEN
      token: 00000000-0000-0000-0000-000000000000
      application-name: appx
      kv:
        enabled: true
        backend: secret
        default-context: appx
  config:
    import: optional:vault://

appx:
  modules:
    vault:
      enabled: true
    services:
      user-auth-service: http://USER-AUTH-SERVICE/api/users

server:
  port: ${VPORT:8080}