version: '3.6'

services:
  localstack:
    domainname: localhost
    hostname: localstack
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566-4597:4566-4597"
      - "${PORT_WEB_UI-8180}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=${LOCALSTACK_SERVICES-kms:4599,dynamodb:4569,s3:4572,sns:4575,sqs:4576}
      - DEBUG=${LOCALSTACK_DEBUG- }
      - DATA_DIR=${LOCALSTACK_DATA_DIR- }
      - PORT_WEB_UI=${LOCALSTACK_PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LOCALSTACK_LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${LOCALSTACK_KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOSTNAME_EXTERNAL=localstack
      - DEFAULT_REGION=us-east-1
    volumes:
      # - "${TMP_DIR:-/tmp}/localstack:/tmp/localstack" # TMP_DIR=/Users/admin/tmp
      - "/var/run/docker.sock:/var/run/docker.sock"

  mongo:
    domainname: localhost
    hostname: mongo
    image: mongo
    container_name: "mongo-server"
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=password

  redis:
    domainname: localhost
    hostname: redis
    image: redis:4.0.2
    container_name: "redis-server"
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - "${TMP_DIR:-/tmp}/bitnami/redis/data:/bitnami/redis/data"
    command: [
      "bash", "-c",
      '
        docker-entrypoint.sh
        --requirepass "redis"
      '
    ]

  localstack-ui:
    domainname: localhost
    hostname: localstack-ui
    image: amitkshirsagar13/localstack-ui
    container_name: "localstack-ui"
    ports:
      - "8001:8001"
      - "8002:8002" # sqs-admin
    environment:
      - DYNAMO_ENDPOINT=http://localstack:4569
      - SQS_ENDPOINT=http://localstack:4576
      - AWS_REGION="us-east-1"
    entrypoint: /bin/sh
    command: -c "env DYNAMO_ENDPOINT=http://localstack:4569 dynamodb-admin & env SQS_ENDPOINT=http://localstack:4576 sqs-admin"
    links:
      - "localstack:localstack"
    depends_on:
      - localstack

  vault:
    domainname: localhost
    hostname: vault
    image: vault:1.13.3
    container_name: "vault"
    ports:
      - "8200:8200"
    volumes:
      - ./vault/policies:/vault/policies
      - ./vault/data:/vault/data
      - ./vault/logs:/vault/logs
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
      - VAULT_TOKEN=00000000-0000-0000-0000-000000000000
    command: server --dev --dev-root-token-id="00000000-0000-0000-0000-000000000000"
    cap_add:
      - IPC_LOCK
    depends_on:
      - consul

  consul:
    domainname: localhost
    hostname: consul:1.15.4
    image: amitkshirsagar13/consul
    container_name: "consul"
    ports:
      - 8500:8500
    command: agent -server -bind 0.0.0.0 -client 0.0.0.0 -bootstrap-expect 1 -config-file=/consul/config/config.json
    volumes:
      - ./consul/config/consul-config.json:/consul/config/config.json
      - ./consul/data:/consul/data
#
#  test-module1:
#    domainname: localhost
#    hostname: test-module1
#    image: amitkshirsagar13/test-module
#    container_name: "test-module1"
#    ports:
#      - 2001:2000
#    environment:
#      - spring.profiles.active=dev
#      - ENVPREFIX=dev1
#      - VAULT_TOKEN=00000000-0000-0000-0000-000000000000
#      - aws.accessKeyId=AKIAIOSFODNN7EXAMPLE
#      - aws.secretKey=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
#      - AWS_ACCESS_KEY_ID=foobar
#      - AWS_SECRET_ACCESS_KEY=foobar
#      - SQS_ENDPOINT=http://localstack:4576
#      - VAULTHOST=vault
#      - CONSULHOST=consul
#      - REDISHOST=redis
#    depends_on:
#      - vault
#      - localstack
#      - redis
#    links:
#      - "localstack:localstack"
#      - "redis:redis"
#      - "consul:consul"
#      - "vault:vault"
#
#  test-module2:
#    domainname: localhost
#    hostname: test-module2
#    image: amitkshirsagar13/test-module
#    container_name: "test-module2"
#    ports:
#      - 2002:2000
#    environment:
#      - spring.profiles.active=dev
#      - ENVPREFIX=dev2
#      - VAULT_TOKEN=00000000-0000-0000-0000-000000000000
#      - aws.accessKeyId=AKIAIOSFODNN7EXAMPLE
#      - aws.secretKey=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
#      - AWS_ACCESS_KEY_ID=foobar
#      - AWS_SECRET_ACCESS_KEY=foobar
#      - SQS_ENDPOINT=http://localstack:4576
#      - VAULTHOST=vault
#      - CONSULHOST=consul
#      - REDISHOST=redis
#    depends_on:
#      - vault
#      - localstack
#      - redis
#    links:
#      - "localstack:localstack"
#      - "redis:redis"
#      - "consul:consul"
#      - "vault:vault"