###
GET https://user-service.appx.localtest.me:8080/basic/api/generate-token
Authorization: Basic YWRtaW46cEBzc3cwcmQ=

### 
GET https://localhost:8080/api/users/e098aaae-ac07-47b5-b084-38e17ecd7f8c
Authorization: eyJhbGciOiJub25lIn0.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlNZU1RFTV9BRE1JTklTVFJBVE9SIiwiT1JHQU5JWkFUSU9OX0FETUlOSVNUUkFUT1IiLCJEQVRBX01BTkFHRVIiLCJDT01QQU5ZX0FETUlOSVNUUkFUT1IiLCJTRVJWSUNFX0FDQ09VTlQiXSwiZW1haWwiOiJhZG1pbkBkZXZvcHNuZXh0Z2VueC5pbyIsImlhdCI6MTczNDg4NzAyMywiZXhwIjoxNzM0ODg3MDI3fQ.
access-data: eyJ1c2VySWQiOiJhbWl0LmtzaGlyc2FnYXIiLCJjb21wYW55SWQiOiJzaWVtZW5zIiwib3JnYW5pemF0aW9uSWQiOiJETVMiLCAicm9sZUxpc3QiOlsiU1lTVEVNX0FETUlOSVNUUkFUT1IiLCJEQVRBX01BTkFHRVIiXX0=

### 
GET https://localhost:8080/api/echo
Authorization: eyJhbGciOiJub25lIn0.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlNZU1RFTV9BRE1JTklTVFJBVE9SIiwiT1JHQU5JWkFUSU9OX0FETUlOSVNUUkFUT1IiLCJEQVRBX01BTkFHRVIiLCJDT01QQU5ZX0FETUlOSVNUUkFUT1IiLCJTRVJWSUNFX0FDQ09VTlQiXSwiZW1haWwiOiJhZG1pbkBkZXZvcHNuZXh0Z2VueC5pbyIsImlhdCI6MTczNDg4NzAyMywiZXhwIjoxNzM0ODg3MDI3fQ.
access-data: eyJ1c2VySWQiOiJhbWl0LmtzaGlyc2FnYXIiLCJjb21wYW55SWQiOiJzaWVtZW5zIiwib3JnYW5pemF0aW9uSWQiOiJETVMiLCAicm9sZUxpc3QiOlsiU1lTVEVNX0FETUlOSVNUUkFUT1IiLCJEQVRBX01BTkFHRVIiXX0=

### 
GET https://localhost:8080/api/users
Authorization: eyJhbGciOiJub25lIn0.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlNZU1RFTV9BRE1JTklTVFJBVE9SIiwiT1JHQU5JWkFUSU9OX0FETUlOSVNUUkFUT1IiLCJEQVRBX01BTkFHRVIiLCJDT01QQU5ZX0FETUlOSVNUUkFUT1IiLCJTRVJWSUNFX0FDQ09VTlQiXSwiZW1haWwiOiJhZG1pbkBkZXZvcHNuZXh0Z2VueC5pbyIsImlhdCI6MTczNDg4NzAyMywiZXhwIjoxNzM0ODg3MDI3fQ.
access-data: eyJ1c2VySWQiOiJhbWl0LmtzaGlyc2FnYXIiLCJjb21wYW55SWQiOiJzaWVtZW5zIiwib3JnYW5pemF0aW9uSWQiOiJETVMiLCAicm9sZUxpc3QiOlsiU1lTVEVNX0FETUlOSVNUUkFUT1IiLCJEQVRBX01BTkFHRVIiXX0=
