###
GET https://user-service.appx.localtest.me:8080/basic/api/generate-token
Authorization: Basic dXNlcjpwYXNzd29yZA==

###
GET https://user-service.appx.localtest.me:8080/api/user/123e4567-e89b-42d3-a456-556642440000
Authorization: eyJhbGciOiJub25lIn0.eyJyb2xlcyI6W3siYXV0aG9yaXR5IjoiUk9MRV9VU0VSIn1dLCJ1c2VlciI6InVzZXIiLCJpYXQiOjE3MzM5NzI3MTAsImV4cCI6MTczMzk3MjcxM30.
access-data: eyJ1c2VySWQiOiJhbWl0LmtzaGlyc2FnYXIiLCJjb21wYW55SWQiOiJzaWVtZW5zIiwib3JnYW5pemF0aW9uSWQiOiJETVMiLCAicm9sZUxpc3QiOlsiU1lTVEVNX0FETUlOSVNUUkFUT1IiLCJEQVRBX01BTkFHRVIiXX0=
