version: '3.6'

services:
  vault:
    image: vault
    container_name: "vault"
    ports:
      - "8200:8200"
    volumes:
      - ./vault/policies:/vault/policies
      - ./vault/data:/vault/data
      - ./vault/logs:/vault/logs
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
      - VAULT_TOKEN="00000000-0000-0000-0000-000000000000"
    command: server --dev --dev-root-token-id="00000000-0000-0000-0000-000000000000"
    cap_add:
      - IPC_LOCK