spring:
  application:
    name: user-auth-module
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: jdbc:mysql://${VDATABASE:mysql.local.localtest.me}:${VPORT:3306}/${AUTHSCHEMA:${user.name}_auth_db}?createDatabaseIfNotExist=true&autoReconnect=true
    name: authdb
    username: root
    password: root
    # username: ${VDBUSER:admin}
    # password: ${VDBPASS:admin123}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      # ddl-auto: update
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false

server:
  hostname: ${VHOSTNAME:${HOSTNAME:authservice.local.localtest.me}}
  port: ${VPORT:2001}
