spring:
  application:
    name: user-auth-service
  datasource:
    url: jdbc:mysql://${VDATABASE:mysql.local.localtest.me}:${VPORT:3306}/${AUTHSCHEMA:${user.name}_auth_db}?createDatabaseIfNotExist=true&autoReconnect=true
    name: authdb
    username: ${VDBUSER:root}
    password: ${VDBPASS:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  hostname: ${VHOSTNAME:${HOSTNAME:authservice.local.localtest.me}}
  port: ${VPORT:2001}

jasypt:
  encryptor:
    password: terces##secret

app:
  modules:
    security:
      secretKey: terces##secret
      encrypted: classpath:encrypted.properties
