spring:
  application:
    name: user-auth-service
  cloud:
    vault:
      port: 8200
      scheme: http
      authentication: TOKEN
      token: 00000000-0000-0000-0000-000000000000
      application-name: appx
      kv:
        enabled: true
        backend: secret
        default-context: appx
  config:
    import: optional:vault://

server:
  port: ${VPORT:2001}

appx:
  modules:
    vault:
      enabled: true
    swagger:
      enabled: true
      title: User Auth Service
      description: User Auth Service
      version: 1.0
      contact:
        name: Amit Kshirsagar
        email: amit.kshirsagar.13@gmail.com