spring:
  application:
    name: user-auth-service
  datasource:
    url: jdbc:mysql://${VDATABASE:mysql.local.localtest.me}:${VPORT:3306}/${AUTHSCHEMA:${user.name}_auth_db}?createDatabaseIfNotExist=true&autoReconnect=true
    name: authdb
    username: ${VDBUSER:root}
    password: ${VDBPASS:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  hostname: ${VHOSTNAME:${HOSTNAME:authservice.local.localtest.me}}
  port: ${VPORT:2001}
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:appx.p12
    key-store-password: appxxppa
    key-alias: appx
