spring:
  application:
    name: app-service

app:
  modules:
    tracing:
      jaeger:
        enabled: false
        host: jaeger-agent.localtest.me
        port: 6831
        trace:
          samplingRate: 1
          flushInterval: 1000
          maxQueueSize: 1000
    security:
      enabled: true
      oauth:
        defaultAuthType: SELFSIGNED
        applications:
          self-signed:
            domain: https://devopsnextgenx.auth0.com/
            dBConnection: SelfSigned-Authentication
            clientId: SelfSigned-Client-ID
            clientSecret: fake-client-secret
            expirationSec: 808080
            notBeforeSec: 4
            issuedAtSec: 4
            authType: SELFSIGNED
    services:
      userServiceHost: http://user-service.localtest.me
    swagger:
      enabled: true
      users:
        swaggerUser: ${SWAGGER_USER:user}
        swaggerUserPassword: ${SWAGGER_USER_PASS:user}
        swaggerAdmin: ${SWAGGER_ADMIN:admin}
        swaggerAdminPassword: ${SWAGGER_ADMIN_PASS:admin}
