spring:
    application:
        name: user-service
    datasource:
        url: jdbc:mysql://localhost:3306/user
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false
        properties:
            hibernate:
                '[dialect]': org.hibernate.dialect.MySQL8Dialect
                '[format_sql]': false

app:
  services:
    userServiceHost: http://user-service.localtest.me
  modules:
    logging:
      enabled: true
    tracing:
      enabled: true
      jaeger:
        enabled: true
        agent:
          jaegerHost: localhost
          jaegerPort: 6831
        trace:
          samplingRate: 1
          flushInterval: 1000
          maxQueueSize: 1000
    security:
      basic:
        enabled: true
        user:
          name: user
          password: password
          role: USER
      jwt:
        enabled: false
  oauth:
    defaultAuthType: SELFSIGNED
    applications:
      # auth0:
      #   authType: AUTH0
      #   domain: https://devopsnextgenx.auth0.com/
      #   clientId: AJn1FDdQtsuolZeU4MIK2O7NbXvjccKN
      #   clientSecret: R40JLeatEu6mMUPAA25IyESgAjMmOUqE9LKI9gzWjejksoUJmoiZJaDzqublAFPw
      #   audience: AJn1FDdQtsuolZeU4MIK2O7NbXvjccKN
      #   redirectUrl: http://devopsnextgenx.localtest.me
      #   dbConnection: Username-Password-Authentication
      # auth0-v2:
      #   authType: AUTH0
      #   domain: https://devopsnextgenx.auth0.com/
      #   clientId: AJn1FDdQtsuolZeU4MIK2O7NbXvjccKN
      #   clientSecret: R40JLeatEu6mMUPAA25IyESgAjMmOUqE9LKI9gzWjejksoUJmoiZJaDzqublAFPw
      #   audience: https://devopsnextgenx.auth0.com/api/v2/
      self-signed:
        authType: SELFSIGNED
        domain: ${AUTH_DOMAIN:https://devopsnextgenx.localtest.me/}
        clientId: ${AUTH_API_V2_clientId:fake-client-id}
        clientSecret: fake-client-secret
  auth:
    swagger:
      swaggerUser: ${SWAGGER_USER:user}
      swaggerUserPassword: ${SWAGGER_USER_PASS:user}
      swaggerAdmin: ${SWAGGER_ADMIN:admin}
      swaggerAdminPassword: ${SWAGGER_ADMIN_PASS:admin}

springdoc:
    api-docs:
        path: /v3/api-docs
        enabled: true
    swagger-ui:
        path: /swagger-ui.html
        enabled: true
        tryItOutEnabled: true
        operationsSorter: method
        tagsSorter: alpha
        filter: true
    packages-to-scan:
    - io.devopsnextgenx.demo.controllers
