spring:
  datasource:
    url: jdbc:mysql://${VDATABASE:mysql.local.localtest.me}:${VPORT:3306}/${AUTHSCHEMA:${user.name}_oauth2_db}?createDatabaseIfNotExist=true&autoReconnect=true
    name: oauth2
    username: ${VDBUSER:root}
    password: ${VDBPASS:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
    properties: 
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  profiles:
    active: native
  flyway:
    enabled: true
    baselineOnMigrate: true
    user: ${VDBPASS:root}
    password: ${VDBPASS:root}
    schemas: ${AUTHSCHEMA:${user.name}_oauth2_db}
    defaultSchema: ${AUTHSCHEMA:${user.name}_oauth2_db}
    cleanDisabled: true
    url: jdbc:mysql://${VDATABASE:mysql.local.localtest.me}:${VPORT:3306}/${AUTHSCHEMA:${user.name}_oauth2_db}?createDatabaseIfNotExist=true&autoReconnect=true
    locations: classpath:db/migration
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - email
              - profile
          github:
            scope:
              - user:email
              - read:user
  web:
    resources:
      static-locations:
      - classpath:/public/
      - classpath:/secure/
      - classpath:/templates/
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML
  # mvc:
  #   static-path-pattern: /content/**

appx:
  modules:
    vault:
      enabled: true
    security:
      enabled: true
      basic:
        enabled: true
        # api:
        #   path: /basic/**

error:
  whitelabel:
    enabled: false

server:
  port: 5000

logging.level.org.flywaydb.core.internal.command.DbMigrate: TRACE
logging.level.org.springframework.security: DEBUG
