/**
 * User
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Data element for User
 */
export interface User { 
    id?: string;
    email: string;
    firstName?: string;
    lastName?: string;
}

