###
GET https://user-service.appx.localtest.me:2001/basic/api/generate-token
Authorization: Basic YWRtaW46cEBzc3cwcmQ=

### 
GET https://localhost:2001/api/users
Authorization: eyJhbGciOiJub25lIn0.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlNZU1RFTV9BRE1JTklTVFJBVE9SIiwiT1JHQU5JWkFUSU9OX0FETUlOSVNUUkFUT1IiLCJEQVRBX01BTkFHRVIiLCJDT01QQU5ZX0FETUlOSVNUUkFUT1IiLCJTRVJWSUNFX0FDQ09VTlQiXSwiZW1haWwiOiJhZG1pbkBkZXZvcHNuZXh0Z2VueC5pbyIsImlhdCI6MTczNDg4NzAyMywiZXhwIjoxNzM0ODg3MDI3fQ.
access-data: eyJ1c2VySWQiOiJhbWl0LmtzaGlyc2FnYXIiLCJjb21wYW55SWQiOiJzaWVtZW5zIiwib3JnYW5pemF0aW9uSWQiOiJETVMiLCAicm9sZUxpc3QiOlsiU1lTVEVNX0FETUlOSVNUUkFUT1IiLCJEQVRBX01BTkFHRVIiXX0=

### 
GET https://localhost:2001/api/users/a9a50115-54f1-4283-92e0-4bb9e544e38e
Authorization: eyJhbGciOiJub25lIn0.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlNZU1RFTV9BRE1JTklTVFJBVE9SIiwiT1JHQU5JWkFUSU9OX0FETUlOSVNUUkFUT1IiLCJEQVRBX01BTkFHRVIiLCJDT01QQU5ZX0FETUlOSVNUUkFUT1IiLCJTRVJWSUNFX0FDQ09VTlQiXSwiZW1haWwiOiJhZG1pbkBkZXZvcHNuZXh0Z2VueC5pbyIsImlhdCI6MTczNDg4NzAyMywiZXhwIjoxNzM0ODg3MDI3fQ.
access-data: eyJ1c2VySWQiOiJhbWl0LmtzaGlyc2FnYXIiLCJjb21wYW55SWQiOiJzaWVtZW5zIiwib3JnYW5pemF0aW9uSWQiOiJETVMiLCAicm9sZUxpc3QiOlsiU1lTVEVNX0FETUlOSVNUUkFUT1IiLCJEQVRBX01BTkFHRVIiXX0=
