openapi: 3.0.0
servers:
  - url: 'http://import-xml.local.localtest.me'
info:
  description: >-
    The ImportXml API.
  version: 1.0.0
  title: ImportXml API
  contact:
    name: Amit Kshirsagar
tags:
  - name: ImportXml
    description: Import data from Xml File with beans Definitions.

security:
  - JwtAuthKey: []

paths:
  /admin/importXml/{mode}:
    put:
      operationId: importXml
      tags:
        - ImportXml
      description: importXml DB with the give mode.
      parameters:
        - name: mode
          in: path
          required: true
          description: mode required
          schema:
            type: string
            example: INCREMENTAL
            enum:
              - INCREMENTAL
              - OVERRIDE
            default: INCREMENTAL
      responses:
        '200':
          $ref: '#/components/responses/XmlImporter'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/404NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  securitySchemes:
    JwtAuthKey:
      type: apiKey
      in: header
      name: Authorization

  responses:
    XmlImporter:
      description: SUCCESS
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/XmlImporter'
    404NotFound:       # Can be referenced as '#/components/responses/404NotFound'
      description: The specified resource was not found.
    BadRequest:
      description: BAD_REQUEST
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/KError'
    Unauthorized:
      description: UNAUTHORIZED
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/KError'
    Forbidden:
      description: FORBIDDEN
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/KError'
    InternalServerError:
      description: INTERNAL_SERVER_ERROR
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/KError'
    ImageResponse:     # Can be referenced as '#/components/responses/ImageResponse'
      description: An image.
      content:
        image/*:
          schema:
            type: string
            format: binary
    GenericError:      # Can be referenced as '#/components/responses/GenericError'
      description: An error occurred.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/KError'

  schemas:
    KError:
      type: object
      properties:
        error:
          type: string
        status:
          type: string
        correlation-id:
          type: string
    Entity:
      type: object
      properties:
        externalId:
          type: string
        message:
          type: string
    EntityList:
      type: object
      properties:
        count:
          type: integer
        entities:
          type: array
          items:
            $ref: '#/components/schemas/Entity'
    XmlImporter:
      allOf:
        - $ref: '#/components/schemas/KError'
        - type: object
          required:
            - toCreate
            - created
            - notCreated
          properties:
            toCreate:
              type: integer
            created:
              type: integer
            updated:
              type: integer
            notCreated:
              $ref: '#/components/schemas/EntityList'
