openapi: 3.0.1

info:
  title: "User"
  version: "1"
  description: User API

servers:
  - url: http://localhost:8080/api
    description: Local server

paths:

  /user:
    post:
      tags:
      - User
      summary: Save User
      operationId: saveUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

  /user/{id}:
    delete:
      tags:
      - User
      summary: Delete User By Id
      operationId: deleteUserById
      parameters:
        - name: id
          in: path
          description: Unique Id of an User
          required: true
          schema:
            type: string
            format: uuid
      responses:
        201:
          description: OK

    get:
      tags:
      - User
      summary: Get User By Id
      operationId: getUserById
      parameters:
        - name: id
          in: path
          description: Unique Id of an User
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

components:
  schemas:
    User:
      type: object
      description: Data element for User
      required:
        - email
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
        firstName:
          type: string
          minLength: 3
        lastName:
          type: string

    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string