openapi: 3.0.0

info:
  title: Auth API
  description: Auth Apis for Appx.
  version: 0.1.9
  contact:
    name: Amit Kshirsagar

servers:
  - url: 'http://auth-service.{environment}.localtest.me'
    variables:
      environment:
        default: api.local    # Local server
        enum:
          - api               # Production server
          - api.dev           # Development server
          - api.local         # Local server
          - api.staging       # Staging server

tags:
  - name: AuthService
    description: Authorization Service

security:
  - JwtAuthKey: []

paths:
  /authorization/authToken:
    get:
      operationId: authToken
      tags:
      - AuthService
      description: Returns the Auth Token
      parameters:
      - name: code
        in: query
        required: true
        description: code required
        schema:
          type: string
      responses:
        200:
          $ref: '#/components/responses/AuthToken'
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/Unauthorized'
        403:
          $ref: '#/components/responses/Forbidden'
        404:
          $ref: '#/components/responses/404NotFound'
        500:
          $ref: '#/components/responses/InternalServerError'


components:
  securitySchemes:
    JwtAuthKey:
      type: apiKey
      in: header
      name: Authorization

  responses:
    404NotFound:       # Can be referenced as '#/components/responses/404NotFound'
      description: The specified resource was not found.
    AuthToken:
      description: SUCCESS
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AuthToken'

    BadRequest:
      description: BAD_REQUEST
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AppxError'
    Unauthorized:
      description: UNAUTHORIZED
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AppxError'
    Forbidden:
      description: FORBIDDEN
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AppxError'
    InternalServerError:
      description: INTERNAL_SERVER_ERROR
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AppxError'
    ImageResponse:     # Can be referenced as '#/components/responses/ImageResponse'
      description: An image.
      content:
        image/*:
          schema:
            type: string
            format: binary

    GenericError:      # Can be referenced as '#/components/responses/GenericError'
      description: An error occurred.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AppxError'

  schemas:
    AppxError:
      type: object
      properties:
        error:
          type: string
        status:
          type: string
        correlation-id:
          type: string

    AuthToken:
      allOf:
      - $ref: '#/components/schemas/AppxError'
      - type: object
        required:
          - accessToken
        properties:
          accessToken:
            type: string
          userName:
            type: string
          userId:
            type: string
