spring:
  datasource:
    url: jdbc:mysql://${VDATABASE:mysql.local.localtest.me}:${VPORT:3306}/${AUTHSCHEMA:${user.name}_oauth2_db}?createDatabaseIfNotExist=true&autoReconnect=true
    name: oauth2
    username: ${VDBUSER:root}
    password: ${VDBPASS:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    baselineOnMigrate: true
    user: ${VDBPASS:root}
    password: ${VDBPASS:root}
    schemas: ${AUTHSCHEMA:${user.name}_oauth2_db}
    defaultSchema: ${AUTHSCHEMA:${user.name}_oauth2_db}
    cleanDisabled: true
    url: jdbc:mysql://${VDATABASE:mysql.local.localtest.me}:${VPORT:3306}/${AUTHSCHEMA:${user.name}_oauth2_db}?createDatabaseIfNotExist=true&autoReconnect=true
    locations: classpath:db/migration
